version: "3.9"

services:
  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media_value:/var/html/media/
      - static_value:/var/html/static/
    depends_on:
      - db

  redis:
    image: redis
    restart: always

  web:
    depends_on:
      - db
    restart: always
    build: ../
    volumes:
      - ../skyeng/templates:/app/templates
      - static_value:/app/static/
      - media_value:/app/media/
      - ./media:/app/media/
    ports:
      - "8000:8000"
    command: ["gunicorn", "skyeng.wsgi:application", "--bind", "0:8000" ]

  worker:
    depends_on:
      - web
    restart: always
    image: rbychin/skyeng:latest
    volumes:
      - ./media:/app/media/
      - ./sent_emails:/app/sent_emails
    command: ["celery", "-A", "skyeng", "worker", "--loglevel=info"]

  celery-beat:
    depends_on:
      - web
    restart: always
    image: rbychin/skyeng:latest
    command: [ "celery", "-A", "skyeng", "beat", "--loglevel=info", "--scheduler=django_celery_beat.schedulers:DatabaseScheduler" ]


volumes:
  postgres_data:
  static_value:
  media_value: